In [1]:
import numpy as np

In [45]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([ [0,0,0,1] ]).T

In [46]:
X.shape,Y.shape

((4, 2), (4, 1))

### Sigmoid 

In [2]:
def sig(z):
    return 1/(1+np.exp(-z))
    
print('e :',np.exp(1)) 

z=np.array([1.0,2.0,3.0])
print(sig(z))

e : 2.718281828459045
[0.73105858 0.88079708 0.95257413]


In [3]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

## No Hidden Layer

### Initialise weights

In [50]:
np.random.seed(10)
weights=2*np.random.random((2,1))-1
bias=2*np.random.random((1,1))-1
weights,bias

(array([[ 0.54264129],
        [-0.9584961 ]]),
 array([[0.26729647]]))

### Forward Propagation Without any Hidden Layer 

In [51]:
output0 = X
output = sig(np.dot(output0,weights)+bias)
output

array([[0.56642907],
       [0.33376626],
       [0.69209624],
       [0.46292857]])

### BackPropagation With out Hidden Layer

In [52]:
first_term = output-Y
input_j = np.dot(output0,weights)+ bias
second_term = derivativeSig(input_j)
first_two = first_term*second_term
first_two.shape

(4, 1)

In [53]:
w_changes=np.array([[0.0],[0.0]])
for i in range(2):
    for j in range(4):
        w_changes[i,0]+=first_two[j,0]*output0[j,i]
        # Why 0 as shape is 4*1 so onlu one column.possible
learningRate = 0.01
weights = weights - learningRate*w_changes
weights , weights.shape

(array([[ 0.54250173],
        [-0.95790299]]),
 (2, 1))

In [54]:
bias_changes=np.array([[0.0]])

for j in range(4):
    bias_changes[0,0]+=first_two[j,0]
        # Why 0 as shape is 4*1 so onlu one column.possible

bias = bias - learningRate*bias_changes
bias , bias.shape

(array([[0.26502366]]), (1, 1))

### Complete Neural Netword

In [61]:
%%time

X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([ [0,0,0,1] ]).T

## Inialise Weights 
np.random.seed(10)
weights=2*np.random.random((2,1))-1
bias=2*np.random.random((1,1))-1

learningRate = 0.1
output0 = X

for iter in range(10000):
    # print(iter)
    output = sig(np.dot(output0,weights)+bias)
    
    first_term = output-Y
    
    input_j = np.dot(output0,weights)+ bias
    second_term = derivativeSig(input_j)
    
    first_two = first_term*second_term
     
    ## Update Weights
    w_changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            w_changes[i][0]+=first_two[j][0]*output0[j][i]
    
    weights = weights - learningRate*w_changes

    ## Update Bias
    bias_changes=np.array([[0.0]])
    for j in range(4):
        bias_changes[0][0]+=first_two[j][0]
            
    bias = bias - learningRate*bias_changes
    
output = sig(np.dot(X,weights)+bias)
weights,bias,output

CPU times: total: 953 ms
Wall time: 992 ms


(array([[5.47310337],
        [5.47310335]]),
 array([[-8.30237529]]),
 array([[2.47865776e-04],
        [5.57627201e-02],
        [5.57627213e-02],
        [9.33629774e-01]]))

In [19]:
%%time

X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([ [0,0,0,1] ]).T

## Inialise Weights 
np.random.seed(10)
weights=2*np.random.random((2,1))-1
bias=2*np.random.random((1,1))-1

learningRate = 0.1
output0 = X

for iter in range(10000):
    # print(iter)
    inputO = np.dot(output0,weights)+bias
    outputO = sig(inputO)
    
    first_term = outputO-Y
    
    input_j = np.dot(output0,weights)+ bias
    second_term = derivativeSig(input_j)
    
    first_two = first_term*second_term
    ## Update Weights
    w_changes=np.dot(output0.T,first_two)
    weights = weights - learningRate*w_changes
    
    ## Update Bias
    bias_changes=np.sum(first_two,axis=0)
    bias = bias - learningRate*bias_changes

inputO = np.dot(output0,weights)+bias
outputO = sig(inputO)
weights,bias,outputO

CPU times: total: 875 ms
Wall time: 898 ms


(array([[5.47310337],
        [5.47310335]]),
 array([[-8.30237529]]),
 array([[2.47865776e-04],
        [5.57627201e-02],
        [5.57627213e-02],
        [9.33629774e-01]]))

## With Hidden Layer

In [64]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[1,0,0,1]]).T

### Initialise weights

In [65]:
np.random.seed(42)
weightsH=2*np.random.random((2,2))-1
biasH=2*np.random.random((1,2))-1
weightsH,biasH

(array([[-0.25091976,  0.90142861],
        [ 0.46398788,  0.19731697]]),
 array([[-0.68796272, -0.68801096]]))

In [66]:
np.random.seed(40)
weightsO=2*np.random.random((2,1))-1
biasO=2*np.random.random((1,1))-1
weightsO,biasO

(array([[-0.18462594],
        [-0.88926792]]),
 array([[0.57706975]]))

### Forward Propagation With Hidden Layer 

In [83]:
output0 = X
inputH = np.dot(output0,weightsH)+biasH
outputH = sig(inputH)
inputO = np.dot(outputH,weightsO)+biasO
outputO = sig(inputO)
outputH,outputO

(array([[0.33448643, 0.33447569],
        [0.4442392 , 0.37973009],
        [0.28112613, 0.55315282],
        [0.38345841, 0.60126401]]),
 array([[0.55425464],
        [0.53926148],
        [0.50831561],
        [0.49289762]]))

### BackPropagation With Hidden Layer

In [23]:
first_term_OutputL = outputO-Y
second_term_OutputL = derivativeSig(inputO)
first_two_OutputL = first_term_OutputL * second_term_OutputL

In [24]:
first_term_HiddenL = np.dot(first_two_OutputL,weightsO.T)
second_term_HiddenL = derivativeSig(inputH)
first_two_HiddenL = first_term_HiddenL * second_term_HiddenL

In [29]:
changes_OutputL_weights = np.dot(outputH.T,first_two_OutputL)
changes_OutputL_bias = np.sum(first_two_OutputL,axis=0,keepdims=True) ## will give vector rather than single number 

changes_HiddenL_weights = np.dot(outputO.T,first_two_HiddenL)
changes_HiddenL_bias = np.sum(first_two_HiddenL,axis=0,keepdims=True) ## will give vector rather than single number 

lr = 0.01
weightsO = weightsO -lr*changes_OutputL_weights
biasO = biasO -lr*changes_OutputL_bias

weightsH = weightsH -lr*changes_HiddenL_weights
biasH = biasH -lr*changes_HiddenL_bias

### Complete General Neural Network

#### NN-I 

In [34]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,0]]).T

np.random.seed(42)

weightsH = 2*np.random.random((2,2))-1
biasH = 2*np.random.random((1,2))-1

weightsO = 2*np.random.random((2,1))-1
biasO = 2*np.random.random((1,1))-1

lr = 0.1
output0 = X

for iter in range(10000):
    
    inputH = np.dot(output0,weightsH)+biasH
    outputH = sig(inputH)
    inputO = np.dot(outputH,weightsO)+biasO
    outputO = sig(inputO)
    
    first_term_OutputL = outputO-Y
    second_term_OutputL = derivativeSig(inputO)
    first_two_OutputL = first_term_OutputL * second_term_OutputL
    
    first_term_HiddenL = np.dot(first_two_OutputL,weightsO.T)
    second_term_HiddenL = derivativeSig(inputH)
    first_two_HiddenL = first_term_HiddenL * second_term_HiddenL
    
    changes_OutputL_weights = np.dot(outputH.T,first_two_OutputL)
    changes_OutputL_bias = np.sum(first_two_OutputL,axis=0,keepdims=True) ## will give vector rather than single number 
    
    changes_HiddenL_weights = np.dot(output0.T,first_two_HiddenL)
    changes_HiddenL_bias = np.sum(first_two_HiddenL,axis=0,keepdims=True) ## will give vector rather than single number 
    
    weightsO = weightsO -lr*changes_OutputL_weights
    biasO = biasO -lr*changes_OutputL_bias
    
    weightsH = weightsH -lr*changes_HiddenL_weights
    biasH = biasH -lr*changes_HiddenL_bias


inputH = np.dot(output0,weightsH)+biasH
outputH = sig(inputH)
inputO = np.dot(outputH,weightsO)+biasO
outputO = sig(inputO)

outputO,weightsH,weightsO,biasH,biasO 

(array([[0.06163868],
        [0.94418828],
        [0.94420396],
        [0.05927355]]),
 array([[3.84775806, 5.51867251],
        [3.84655814, 5.5141638 ]]),
 array([[-7.90825684],
        [ 7.37465969]]),
 array([[-5.90851032, -2.31351363]]),
 array([[-3.36521572]]))

#### NN-II

In [163]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,0]]).T

np.random.seed(42)

weightsH = 2*np.random.random((2,4))-1
biasH = 2*np.random.random((1,4))-1

weightsO = 2*np.random.random((4,1))-1
biasO = 2*np.random.random((1,1))-1

lr = 0.1
output0 = X

for iter in range(10000):
    
    inputH = np.dot(output0,weightsH)+biasH
    outputH = sig(inputH)
    inputO = np.dot(outputH,weightsO)+biasO
    outputO = sig(inputO)
    
    first_term_OutputL = outputO-Y
    second_term_OutputL = derivativeSig(inputO)
    first_two_OutputL = first_term_OutputL * second_term_OutputL
    
    changes_OutputL_weights = np.dot(outputH.T,first_two_OutputL)
    changes_OutputL_bias = np.sum(first_two_OutputL,axis=0,keepdims=True) ## will give vector rather than single number 
    
    weightsO = weightsO -lr*changes_OutputL_weights
    biasO = biasO -lr*changes_OutputL_bias
    
    first_term_HiddenL = np.dot(first_two_OutputL,weightsO.T)
    second_term_HiddenL = derivativeSig(inputH)
    first_two_HiddenL = first_term_HiddenL * second_term_HiddenL
    
    changes_HiddenL_weights = np.dot(output0.T,first_two_HiddenL)
    changes_HiddenL_bias = np.sum(first_two_HiddenL,axis=0,keepdims=True) ## will give vector rather than single number 
    
    weightsH = weightsH -lr*changes_HiddenL_weights
    biasH = biasH -lr*changes_HiddenL_bias


inputH = np.dot(output0,weightsH)+biasH
outputH = sig(inputH)
inputO = np.dot(outputH,weightsO)+biasO
outputO = sig(inputO)

outputO,weightsH,weightsO,biasH,biasO 

(array([[0.04185399],
        [0.95113438],
        [0.95441066],
        [0.04800054]]),
 array([[ 4.5109361 ,  5.66190921, -1.13713739,  0.85868769],
        [-5.12642605, -5.31381498, -1.17077569,  0.97193533]]),
 array([[ 7.70407925],
        [-7.33482918],
        [-0.92231126],
        [ 1.57701299]]),
 array([[-2.37537617,  2.78731873, -0.95504034,  1.03731628]]),
 array([[2.21504019]]))

#### Functions 

In [4]:
def getHiddenWeightsBias(num_hidden , n_feature ):
    np.random.seed(10)
    HLW = np.random.random((n_feature,num_hidden[0]))
    HLB = np.random.random((1,num_hidden[0]))
    List1 =[HLW]
    List2 =[HLB]
    n = len(num_hidden)
    j=1
    while(j<n):
        HLW = np.random.random((num_hidden[j-1],num_hidden[j]))
        HLB = np.random.random((1,num_hidden[j]))
        List1.append(HLW)
        List2.append(HLB)
        j+=1
    return List1,List2


In [5]:
def farwardProagation(X,weights,bias):
    LayerOutputs = [X]
    LayerInputs = [X]
    
    j=0
    n = len(weights)
    while j<n:
        input = np.dot(LayerOutputs[-1],weights[j])+bias[j]
        output = sig(input)
        LayerOutputs.append(output)
        LayerInputs.append(input)
        j+=1
        
    return LayerOutputs ,LayerInputs  


In [6]:
def backwardPropagation1(Y,weights,bias,outputs,inputs,lr):

    first_term = outputs[-1]-Y  # First Term of Output Layer
    
    second_term = derivativeSig(inputs[-1])
    first_two = first_term * second_term

    changes_OutputL_weights = np.dot(outputs[-2].T , first_two)
    changes_OutputL_bias = np.sum(first_two ,axis=0 ,keepdims=True) ## will give vector rather than single number 
    
    weights[-1] = weights[-1] -lr*changes_OutputL_weights
    bias[-1] = bias[-1] - lr * changes_OutputL_bias
    
    j= len(weights)-1
    while j>0:
        first_term = np.dot( first_two ,weights[j].T )
        
        second_term = derivativeSig( inputs[j] )
        first_two = first_term * second_term
        
        changes_HiddenL_weights = np.dot(outputs[j-1].T ,first_two)
        changes_HiddenL_bias = np.sum(first_two ,axis = 0 ,keepdims = True) ## will give vector rather than single number 
        
        weights[j-1] = weights[j-1] -lr*changes_HiddenL_weights
        bias[j-1] = bias[j-1] -lr*changes_HiddenL_bias

        j-=1
    return weights,bias

In [7]:
def backwardPropagation2(Y,weights,bias,outputs,inputs,lr):

    first_term = outputs[-1]-Y  # First Term of Output Layer
    
    j= len(weights)-1
    while j>=0:
        
        second_term = derivativeSig( inputs[j+1] )
        first_two = first_term * second_term
        
        changes_HiddenL_weights = np.dot(outputs[j].T ,first_two)
        changes_HiddenL_bias = np.sum(first_two ,axis = 0 ,keepdims = True) ## will give vector rather than single number 
        
        weights[j] = weights[j] -lr*changes_HiddenL_weights
        bias[j] = bias[j] -lr*changes_HiddenL_bias

        if(j>0):
            first_term = np.dot( first_two ,weights[j].T ) 
            ## just find first_Term for previpus layer  from first_two of this layer
        j-=1
    return weights,bias

#### NN-III

In [182]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,0]]).T
lr = 1

num_hidden=[5,4,]
n_output = 1

num_hidden += [n_output]
n_feature = X.shape[1]

weights ,bias = getHiddenWeightsBias(num_hidden,n_feature) 

print("Shape of Weights and biases :",len(weights))
print("Shape of Outputs and Inputs :",len(outputs))
## output size is +1 than weights as it contains X at output[0] and input[0]

for iter in range(10000):
    outputs,inputs = farwardProagation(X,weights,bias)
    weights,bias  = backwardPropagation2(Y,weights,bias,outputs,inputs,lr)


weights ,bias
outputs,inputs
outputs[-1]


Shape of Weights and biases : 3
Shape of Outputs and Inputs : 4


array([[0.00749631],
       [0.99327712],
       [0.9938576 ],
       [0.00720713]])

#### NN-IV

In [183]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,0],[1,0,0,1],[1,0,1,0]]).T
print(X.shape,Y.shape,'\n')
lr = 1

num_hidden=[5,4,]
n_output = 1

num_hidden += [n_output]
n_feature = X.shape[1]

weights ,bias = getHiddenWeightsBias(num_hidden,n_feature) 

print("Shape of Weights and biases :",len(weights))
print("Shape of Outputs and Inputs :",len(outputs))
print()
## output size is +1 than weights as it contains X at output[0] and input[0]

for i in range(len(bias)):
    print(weights[i].shape,bias[i].shape)
print()

for iter in range(10000):
    
    outputs,inputs = farwardProagation(X,weights,bias)
    weights,bias  = backwardPropagation2(Y,weights,bias,outputs,inputs,lr)

for i in range(len(bias)):
    print(weights[i].shape,bias[i].shape)
print()

weights ,bias
outputs,inputs
outputs[-1]

(4, 2) (4, 3) 

Shape of Weights and biases : 3
Shape of Outputs and Inputs : 4

(2, 5) (1, 5)
(5, 4) (1, 4)
(4, 1) (1, 1)

(2, 5) (1, 5)
(5, 4) (1, 4)
(4, 3) (1, 3)



array([[7.23388120e-03, 9.92668645e-01, 9.99348796e-01],
       [9.91649846e-01, 8.19296837e-03, 1.07604746e-02],
       [9.90457006e-01, 9.65096403e-03, 9.89549616e-01],
       [1.04269856e-02, 9.89615019e-01, 6.18970565e-04]])

#### NN-V : Neural Network Functions 

In [286]:
def predict(X,weights , bias):

    output = X
    for w,b in zip(weights,bias):
        input = np.dot(output,w) +b
        output = sig(input)
        
    return output

In [352]:
def NeuralNetwork(X,Y,num_hidden,lr,iterations):

    n_output = Y.shape[1]
    n_feature = X.shape[1]
    
    num_hidden += [n_output]
    
    weights ,bias = getHiddenWeightsBias(num_hidden,n_feature) 
   
    for iter in range(iterations):
        outputs,inputs = farwardProagation(X,weights,bias)
        weights,bias  = backwardPropagation2(Y,weights,bias,outputs,inputs,lr)
        
    return weights,bias


In [441]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,0],[1,0,0,1],[1,0,1,0]]).T
Y_=np.array([[0,0,0,1],[1,1,1,0]]).T

num_hidden= []
lr = 0.1
iters = 10000
weights,bias = NeuralNetwork(X,Y_,num_hidden ,lr , iters)
Y_pred = predict(X,weights,bias)
Y_pred

array([[2.45452563e-04, 9.99752182e-01],
       [5.55922322e-02, 9.44240658e-01],
       [5.55922323e-02, 9.44240657e-01],
       [9.33834020e-01, 6.63661785e-02]])

### Iris Dataset 

In [457]:
def Transform(Y):
    uniq = np.unique(Y)
    n = len(uniq)
    
    label_to_index = {}
    index_to_label = {}
    
    index = 0 
    while index < n:
        label = uniq[index]
        
        label_to_index[label] = index
        index_to_label[index ] = label
        index += 1

    Arr = []
    for label in  Y:
        vector = np.zeros(n)
        index = label_to_index[label]
        vector[index] = 1
        Arr.append(vector)
        
    return np.array(Arr),index_to_label  
    
def InverseTransform(Y,index_to_label):

    Arr = []    
    for vector in  Y:
        index = np.argmax(vector)
        label = index_to_label[index]
        Arr.append(label)

    return np.array(Arr) 

In [501]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris.data
Y = iris.target

np.shape(X) , np.shape(Y)

((150, 4), (150,))

In [502]:
from sklearn.model_selection import train_test_split
X_train ,X_test , Y_train,Y_test = train_test_split(X ,Y ,stratify=Y ,random_state = 42,shuffle=True) 


In [503]:
Y_train_t,index_to_label =  Transform(Y_train)
print(Y_train_t[70:75])

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [1007]:
%%time 

lr = 0.005
num_hidden=[2,3]
iterations=10000
# lr = 0.005
# num_hidden=[]
# iterations=10000

weights,bias = NeuralNetwork(X_train,Y_train_t,num_hidden,lr,iterations)

CPU times: total: 3.11 s
Wall time: 3.16 s


In [1008]:
Y_train_pred_t  = predict(X_train ,weights,bias)
Y_test_pred_t  = predict(X_test ,weights,bias)

Y_train_pred_t[19:23]

array([[5.93377348e-03, 8.95621271e-01, 2.79828656e-02],
       [2.01471568e-02, 9.56035459e-01, 5.21833094e-03],
       [7.09364403e-03, 9.12756393e-01, 2.11639547e-02],
       [9.30653402e-01, 8.39055514e-02, 2.61730217e-04]])

In [1009]:
Y_train_pred =  InverseTransform(Y_train_pred_t ,index_to_label)
Y_test_pred = InverseTransform(Y_test_pred_t ,index_to_label)


In [1010]:
from sklearn.metrics import confusion_matrix , classification_report
print(confusion_matrix(Y_train , Y_train_pred))
print(classification_report(Y_train, Y_train_pred))

[[38  0  0]
 [ 0 34  3]
 [ 0  1 36]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.97      0.92      0.94        37
           2       0.92      0.97      0.95        37

    accuracy                           0.96       112
   macro avg       0.96      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112



In [1011]:
print(confusion_matrix(Y_test , Y_test_pred))
print(classification_report(Y_test , Y_test_pred))

[[12  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



## Neural Network Classifier Class 

In [2]:
class OneHot_Encoder:
    def __init__(self):
        pass

    def fit(self,Y):
        uniq = np.unique(Y)
        self.n = len(uniq)
        
        self.label_to_index = {}
        self.index_to_label = {}
        
        index = 0 
        while index < self.n:
            label = uniq[index]
            
            self.label_to_index[label] = index
            self.index_to_label[index ] = label
            index += 1
            
    def transform(self,Y):
        Arr = []
        for label in  Y:
            vector = np.zeros(self.n)
            index = self.label_to_index[label]
            vector[index] = 1
            Arr.append(vector)
            
        return np.array(Arr)
        
    def fit_transform(self,Y):
        self.fit(Y) 
        Y_ = self.transform(Y)
        return Y_
    
        
    def inverse_transform(self,Y):
        Arr = []    
        for vector in  Y:
            index = np.argmax(vector)
            label = self.index_to_label[index]
            Arr.append(label)
            
        return np.array(Arr) 


In [7]:
from sklearn.metrics import log_loss,confusion_matrix,classification_report

class NNClassifier:
    def __init__(self,num_hidden=[2,3] , learning_rate = 0.01 , n_iters=1000 ,random_state=10):
        self.num_hidden = num_hidden
        self.n_iters = n_iters
        self.random_state = random_state
        self.encoder = OneHot_Encoder()
        n_layer = len(num_hidden)+1
        lr = learning_rate 
        if(len(np.shape(learning_rate))==0):
            lr  = np.full(n_layer , learning_rate)
        elif (len(learning_rate)==n_layer):
            lr = learning_rate
        else:
            print("Error with Learning Rate !!")
        self.lr = lr 
            
  ##...Activation Function............................................................................  
    def _sig(self,z):
        return 1/(1+np.exp(-z))

    def _derivativeSig(self,z):
        return self._sig(z)*(1-self._sig(z))

    ## -----Fit-----------------------------------------------------------------------------------
    
    def _TakeRandomWeightsBias(self,n_feature,n_output):
        
        np.random.seed(self.random_state)
        
        num_layers = self.num_hidden + [n_output]
        
        HLW = np.random.random((n_feature,num_layers[0]))
        HLB = np.random.random((1,self.num_hidden[0]))
        List1 =[HLW]
        List2 =[HLB]
        
        n = len(num_layers)
        j=1
        while(j<n):
            HLW = np.random.random((num_layers[j-1],num_layers[j]))
            HLB = np.random.random((1,num_layers[j]))
            List1.append(HLW)
            List2.append(HLB)
            j+=1

        self.weights = List1
        self.bias = List2
        return
    
    def _farwardProagation(self):
        LayerOutputs = [self._X]
        LayerInputs = [self._X]
        
        j=0
        n = len(self.weights)
        while j<n:
            input = np.dot( LayerOutputs[-1] , self.weights[j] ) + self.bias[j]
            output = self._sig(input)
            LayerOutputs.append(output)
            LayerInputs.append(input)
            j+=1

        self._outputs = LayerOutputs
        self._inputs = LayerInputs
        return 

    def _backwardPropagation(self):
        outputs =  self._outputs
        inputs =  self._inputs
        
        first_term = outputs[-1] - self._Y # First Term of Output Layer
        
        j = len(self.weights)-1
        
        while j>=0:
            
            second_term = self._derivativeSig( inputs[j+1] )
            first_two = first_term * second_term
            
            changes_HiddenL_weights = np.dot(outputs[j].T ,first_two)
            changes_HiddenL_bias = np.sum(first_two ,axis = 0 ,keepdims = True) ## will give vector rather than single number 

            print(self.lr[j] * changes_HiddenL_weights)
            print(self.lr[j] * changes_HiddenL_bias)
            print()
            
            self.weights[j] -= self.lr[j] * changes_HiddenL_weights
            self.bias[j] -= self.lr[j] * changes_HiddenL_bias
    
            if(j>0):   ## as j==0 it will be useless to find first term ..
                
                first_term = np.dot( first_two ,self.weights[j].T ) 
                ## just find first_Term for previpus layer  from first_two of this layer
            j-=1
            
        return 
        
    def fit(self,X,Y):
        Y_t = self.encoder.fit_transform(Y)

        n_feature = X.shape[1]  
        n_output = Y_t.shape[1]
        self._TakeRandomWeightsBias(n_feature,n_output) 

        self._X = X
        self._Y = Y_t
        for iter in range(self.n_iters ):
            self._farwardProagation()
            self._backwardPropagation()
            # print(iter)
            print(iter,1000*log_loss(Y,self.predictProb(X)))
    
        delattr(self,'_X')     ## As All now useless . of No use 
        delattr(self,'_Y')
        delattr(self,'_outputs')     ## As All now useless . of No use 
        delattr(self,'_inputs')
        return 
    
    ## -----Predict-----------------------------------------------------------------------------------
    def predict(self,X):
        Y_pred_t = self.predictProb(X)
        Y_pred = self.encoder.inverse_transform(Y_pred_t)
        return Y_pred
        
    def predictProb(self,X):
        output = X
        for w,b in zip( self.weights , self.bias):
            input = np.dot(output,w) +b
            output = self._sig(input)
        Sum = np.sum(output,axis=1,keepdims=True)
        output/=Sum
        return output
## ----Score ----------------------------------------------------------------------------------
    def metric(self,X,Y):
        Y_pred = self.predict(X)
        
        print(confusion_matrix(Y, Y_pred))
        print(classification_report(Y, Y_pred))

In [8]:
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [9]:
from sklearn.model_selection import train_test_split
X_train ,X_test , Y_train,Y_test = train_test_split(X ,Y ,stratify=Y ,random_state = 42,shuffle=True) 
print(X_train.shape)
print(X_test.shape)

(112, 4)
(38, 4)


In [10]:
%%time
## Without Any Hidden Layer 
# lr = 0.005
# num_hidden=[]
# iterations=10000

# # With Hidden Layers 
# lr = 0.005
# num_hidden=[2,3]
# iterations=10000

# With Hidden Layers 
lr = 0.006
num_hidden=[4,3]
iterations=9

## Multiple Hidden Layers
# lr = np.array([1,1,1,10])*0.01
# num_hidden=[2,3,7]
# iterations=5000

clf = NNClassifier(num_hidden=num_hidden,learning_rate=lr,n_iters=iterations)
clf.fit(X_train,Y_train)

[[0.04744844 0.04533994 0.03019006]
 [0.04425067 0.04223066 0.02810578]
 [0.04353463 0.04153103 0.02763627]]
[[0.04920896 0.04709552 0.03137764]]

[[0.00145695 0.00407753 0.00739389]
 [0.00126539 0.00349425 0.00657159]
 [0.00145685 0.00407561 0.00739508]
 [0.00145817 0.00408133 0.00739882]]
[[0.00145828 0.0040818  0.00739913]]

[[1.72798962e-05 3.53888630e-03 3.27821042e-05 2.94003180e-06]
 [9.71018736e-06 1.94951817e-03 2.18879341e-05 1.96246101e-06]
 [9.23500869e-06 1.99509106e-03 1.07184823e-05 9.28810876e-07]
 [2.60360612e-06 5.82303486e-04 1.93165756e-06 1.55984492e-07]]
[[3.22034302e-06 6.31258424e-04 6.61720244e-06 6.02669395e-07]]

0 1101.375434566418
[[0.04920334 0.04796378 0.03258253]
 [0.04580829 0.04459251 0.03027673]
 [0.04496867 0.04375559 0.02970391]]
[[0.05104088 0.04983897 0.03387713]]

[[0.00135113 0.00389921 0.00743689]
 [0.0011645  0.00330819 0.0065917 ]
 [0.00135104 0.00389707 0.0074383 ]
 [0.0013523  0.00390299 0.00744179]]
[[0.0013524  0.00390348 0.00744208]]

[[

In [50]:
Y_train_pred = clf.predict(X_train)
Y_train_pred

array([2, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0, 1, 1, 1,
       0, 1, 2, 0, 2, 1, 2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 2, 2,
       0, 2, 1, 0, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 2, 1, 2, 2, 2, 0, 1,
       0, 2, 1, 2, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 1, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 2, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0, 0, 0, 0,
       1, 0])

In [51]:
clf.metric(X_train,Y_train)

[[38  0  0]
 [ 0 33  4]
 [ 0  0 37]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       1.00      0.89      0.94        37
           2       0.90      1.00      0.95        37

    accuracy                           0.96       112
   macro avg       0.97      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112



In [52]:
clf.metric(X_test,Y_test)

[[12  0  0]
 [ 0 11  2]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.85      0.92        13
           2       0.87      1.00      0.93        13

    accuracy                           0.95        38
   macro avg       0.96      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38



## Practice  

In [1044]:
len(np.shape(10))

0